# Generated by Django 5.2.4 on 2025-07-31 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RespostaUnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcao', models.CharField(choices=[('conectaserv', 'ConectaServ - Sua vida funcional na palma da mão'), ('gdfservidor', 'GDF Servidor - Feito para quem trabalha pelo DF'), ('servigdf', 'ServiGDF - O aplicativo do servidor do GDF'), ('gdfacil', 'GDFácil - Mais agilidade para a vida do servidor do GDF'), ('meugdf', 'MeuGDF - Feito para os servidores do DF')], max_length=20)),
                ('data_submissao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
